
import { Outfit, Inter } from "next/font/google"; // ✅ Import Inter
import "./globals.css";
import Header from "./_components/Header";
import NextAuthSessionProvider from "./provider"

const outfitFont = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const interFont = Inter({ subsets: ["latin"] }); // ✅ Initialize Inter

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={interFont.className}>
        {" "}
        
        <NextAuthSessionProvider>
          <div className="mx-6 md:mx-16">
            <Header />
            {children}
          </div>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
